name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test:ci
      - name: Lint code
        run: pnpm lint
      - name: Build project
        run: pnpm run build
      - name: Publish package to NPM
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
