name: Publish to NPM

on:
  push:
    branches:
      - main # Only run on pushes to the main branch
    tags:
      - '*.*.*' # Stable releases
      - '*-alpha.*' # Alpha releases
      - '*-beta.*' # Beta releases
      - '*-canary.*' # Canary releases

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test:ci
      - name: Lint code
        run: pnpm lint
      - name: Build project
        run: pnpm run build
      - name: Publish package to NPM
        run: |
          if [[ "${{ github.ref }}" == refs/tags/*-alpha* ]]; then
            pnpm publish --access public --tag alpha
          elif [[ "${{ github.ref }}" == refs/tags/*-beta* ]]; then
            pnpm publish --access public --tag beta
          elif [[ "${{ github.ref }}" == refs/tags/*-canary* ]]; then
            pnpm publish --access public --tag canary
          else
            pnpm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}